FROM tomcat
COPY target/*.war /usr/local/tomcat/webapps/
RUN rm -rf /usr/local/tomcat/webapps/ROOT && mv /usr/local/tomcat/webapps/*.war /usr/local/tomcat/webapps/ROOT.war


#This dockerfile use the .war artifact from jenkins server workspace and build image, then push to dockerhub.
